/// <reference path="../cs2.d.ts" />
/// <reference path="../gamevals.d.ts" />
/// <reference path="../vars.d.ts" />
// cs2_1844

function cs2_1844(intArg0: number): number {
    switch (intArg0) {
        case 0:
            return varc_quickchat_listdialog_000;
        case 1:
            return varc_quickchat_listdialog_001;
        case 2:
            return varc_quickchat_listdialog_002;
        case 3:
            return varc_quickchat_listdialog_003;
        case 4:
            return varc_quickchat_listdialog_004;
        case 5:
            return varc_quickchat_listdialog_005;
        case 6:
            return varc_quickchat_listdialog_006;
        case 7:
            return varc_quickchat_listdialog_007;
        case 8:
            return varc_quickchat_listdialog_008;
        case 9:
            return varc_quickchat_listdialog_009;
        case 10:
            return varc_quickchat_listdialog_010;
        case 11:
            return varc_quickchat_listdialog_011;
        case 12:
            return varc_quickchat_listdialog_012;
        case 13:
            return varc_quickchat_listdialog_013;
        case 14:
            return varc_quickchat_listdialog_014;
        case 15:
            return varc_quickchat_listdialog_015;
        case 16:
            return varc_quickchat_listdialog_016;
        case 17:
            return varc_quickchat_listdialog_017;
        case 18:
            return varc_quickchat_listdialog_018;
        case 19:
            return varc_quickchat_listdialog_019;
        case 20:
            return varc_quickchat_listdialog_020;
        case 21:
            return varc_quickchat_listdialog_021;
        case 22:
            return varc_quickchat_listdialog_022;
        case 23:
            return varc_quickchat_listdialog_023;
        case 24:
            return varc_quickchat_listdialog_024;
        case 25:
            return varc_quickchat_listdialog_025;
        case 26:
            return varc_quickchat_listdialog_026;
        case 27:
            return varc_quickchat_listdialog_027;
        case 28:
            return varc_quickchat_listdialog_028;
        case 29:
            return varc_quickchat_listdialog_029;
        case 30:
            return varc_quickchat_listdialog_030;
        case 31:
            return varc_quickchat_listdialog_031;
        case 32:
            return varc_quickchat_listdialog_032;
        case 33:
            return varc_quickchat_listdialog_033;
        case 34:
            return varc_quickchat_listdialog_034;
        case 35:
            return varc_quickchat_listdialog_035;
        case 36:
            return varc_quickchat_listdialog_036;
        case 37:
            return varc_quickchat_listdialog_037;
        case 38:
            return varc_quickchat_listdialog_038;
        case 39:
            return varc_quickchat_listdialog_039;
        case 40:
            return varc_quickchat_listdialog_040;
        case 41:
            return varc_quickchat_listdialog_041;
        case 42:
            return varc_quickchat_listdialog_042;
        case 43:
            return varc_quickchat_listdialog_043;
        case 44:
            return varc_quickchat_listdialog_044;
        case 45:
            return varc_quickchat_listdialog_045;
        case 46:
            return varc_quickchat_listdialog_046;
        case 47:
            return varc_quickchat_listdialog_047;
        case 48:
            return varc_quickchat_listdialog_048;
        case 49:
            return varc_quickchat_listdialog_049;
        case 50:
            return varc_quickchat_listdialog_050;
        case 51:
            return varc_quickchat_listdialog_051;
        case 52:
            return varc_quickchat_listdialog_052;
        case 53:
            return varc_quickchat_listdialog_053;
        case 54:
            return varc_quickchat_listdialog_054;
        case 55:
            return varc_quickchat_listdialog_055;
        case 56:
            return varc_quickchat_listdialog_056;
        case 57:
            return varc_quickchat_listdialog_057;
        case 58:
            return varc_quickchat_listdialog_058;
        case 59:
            return varc_quickchat_listdialog_059;
        case 60:
            return varc_quickchat_listdialog_060;
        case 61:
            return varc_quickchat_listdialog_061;
        case 62:
            return varc_quickchat_listdialog_062;
        case 63:
            return varc_quickchat_listdialog_063;
        case 64:
            return varc_quickchat_listdialog_064;
        case 65:
            return varc_quickchat_listdialog_065;
        case 66:
            return varc_quickchat_listdialog_066;
        case 67:
            return varc_quickchat_listdialog_067;
        case 68:
            return varc_quickchat_listdialog_068;
        case 69:
            return varc_quickchat_listdialog_069;
        case 70:
            return varc_quickchat_listdialog_070;
        case 71:
            return varc_quickchat_listdialog_071;
        case 72:
            return varc_quickchat_listdialog_072;
        case 73:
            return varc_quickchat_listdialog_073;
        case 74:
            return varc_quickchat_listdialog_074;
        case 75:
            return varc_quickchat_listdialog_075;
        case 76:
            return varc_quickchat_listdialog_076;
        case 77:
            return varc_quickchat_listdialog_077;
        case 78:
            return varc_quickchat_listdialog_078;
        case 79:
            return varc_quickchat_listdialog_079;
        case 80:
            return varc_quickchat_listdialog_080;
        case 81:
            return varc_quickchat_listdialog_081;
        case 82:
            return varc_quickchat_listdialog_082;
        case 83:
            return varc_quickchat_listdialog_083;
        case 84:
            return varc_quickchat_listdialog_084;
        case 85:
            return varc_quickchat_listdialog_085;
        case 86:
            return varc_quickchat_listdialog_086;
        case 87:
            return varc_quickchat_listdialog_087;
        case 88:
            return varc_quickchat_listdialog_088;
        case 89:
            return varc_quickchat_listdialog_089;
        case 90:
            return varc_quickchat_listdialog_090;
        case 91:
            return varc_quickchat_listdialog_091;
        case 92:
            return varc_quickchat_listdialog_092;
        case 93:
            return varc_quickchat_listdialog_093;
        case 94:
            return varc_quickchat_listdialog_094;
        case 95:
            return varc_quickchat_listdialog_095;
        case 96:
            return varc_quickchat_listdialog_096;
        case 97:
            return varc_quickchat_listdialog_097;
        case 98:
            return varc_quickchat_listdialog_098;
        case 99:
            return varc_quickchat_listdialog_099;
        case 100:
            return varc_quickchat_listdialog_100;
        case 101:
            return varc_quickchat_listdialog_101;
        case 102:
            return varc_quickchat_listdialog_102;
        case 103:
            return varc_quickchat_listdialog_103;
        case 104:
            return varc_quickchat_listdialog_104;
        case 105:
            return varc_quickchat_listdialog_105;
        case 106:
            return varc_quickchat_listdialog_106;
        case 107:
            return varc_quickchat_listdialog_107;
        case 108:
            return varc_quickchat_listdialog_108;
        case 109:
            return varc_quickchat_listdialog_109;
        case 110:
            return varc_quickchat_listdialog_110;
        case 111:
            return varc_quickchat_listdialog_111;
        case 112:
            return varc_quickchat_listdialog_112;
        case 113:
            return varc_quickchat_listdialog_113;
        case 114:
            return varc_quickchat_listdialog_114;
        case 115:
            return varc_quickchat_listdialog_115;
        case 116:
            return varc_quickchat_listdialog_116;
        case 117:
            return varc_quickchat_listdialog_117;
        case 118:
            return varc_quickchat_listdialog_118;
        case 119:
            return varc_quickchat_listdialog_119;
        case 120:
            return varc_quickchat_listdialog_120;
        case 121:
            return varc_quickchat_listdialog_121;
        case 122:
            return varc_quickchat_listdialog_122;
        case 123:
            return varc_quickchat_listdialog_123;
        case 124:
            return varc_quickchat_listdialog_124;
        case 125:
            return varc_quickchat_listdialog_125;
        case 126:
            return varc_quickchat_listdialog_126;
        case 127:
            return varc_quickchat_listdialog_127;
        case 128:
            return varc_quickchat_listdialog_128;
        case 129:
            return varc_quickchat_listdialog_129;
        case 130:
            return varc_quickchat_listdialog_130;
        case 131:
            return varc_quickchat_listdialog_131;
        case 132:
            return varc_quickchat_listdialog_132;
        case 133:
            return varc_quickchat_listdialog_133;
        case 134:
            return varc_quickchat_listdialog_134;
        case 135:
            return varc_quickchat_listdialog_135;
        case 136:
            return varc_quickchat_listdialog_136;
        case 137:
            return varc_quickchat_listdialog_137;
        case 138:
            return varc_quickchat_listdialog_138;
        case 139:
            return varc_quickchat_listdialog_139;
        case 140:
            return varc_quickchat_listdialog_140;
        case 141:
            return varc_quickchat_listdialog_141;
        case 142:
            return varc_quickchat_listdialog_142;
        case 143:
            return varc_quickchat_listdialog_143;
        case 144:
            return varc_quickchat_listdialog_144;
        case 145:
            return varc_quickchat_listdialog_145;
        case 146:
            return varc_quickchat_listdialog_146;
        case 147:
            return varc_quickchat_listdialog_147;
        case 148:
            return varc_quickchat_listdialog_148;
        case 149:
            return varc_quickchat_listdialog_149;
        case 150:
            return varc_quickchat_listdialog_150;
        case 151:
            return varc_quickchat_listdialog_151;
        case 152:
            return varc_quickchat_listdialog_152;
        case 153:
            return varc_quickchat_listdialog_153;
        case 154:
            return varc_quickchat_listdialog_154;
        case 155:
            return varc_quickchat_listdialog_155;
        case 156:
            return varc_quickchat_listdialog_156;
        case 157:
            return varc_quickchat_listdialog_157;
        case 158:
            return varc_quickchat_listdialog_158;
        case 159:
            return varc_quickchat_listdialog_159;
        case 160:
            return varc_quickchat_listdialog_160;
        case 161:
            return varc_quickchat_listdialog_161;
        case 162:
            return varc_quickchat_listdialog_162;
        case 163:
            return varc_quickchat_listdialog_163;
        case 164:
            return varc_quickchat_listdialog_164;
        case 165:
            return varc_quickchat_listdialog_165;
        case 166:
            return varc_quickchat_listdialog_166;
        case 167:
            return varc_quickchat_listdialog_167;
        case 168:
            return varc_quickchat_listdialog_168;
        case 169:
            return varc_quickchat_listdialog_169;
        case 170:
            return varc_quickchat_listdialog_170;
        case 171:
            return varc_quickchat_listdialog_171;
        case 172:
            return varc_quickchat_listdialog_172;
        case 173:
            return varc_quickchat_listdialog_173;
        case 174:
            return varc_quickchat_listdialog_174;
        case 175:
            return varc_quickchat_listdialog_175;
        case 176:
            return varc_quickchat_listdialog_176;
        case 177:
            return varc_quickchat_listdialog_177;
        case 178:
            return varc_quickchat_listdialog_178;
        case 179:
            return varc_quickchat_listdialog_179;
        case 180:
            return varc_quickchat_listdialog_180;
        case 181:
            return varc_quickchat_listdialog_181;
        case 182:
            return varc_quickchat_listdialog_182;
        case 183:
            return varc_quickchat_listdialog_183;
        case 184:
            return varc_quickchat_listdialog_184;
        case 185:
            return varc_quickchat_listdialog_185;
        case 186:
            return varc_quickchat_listdialog_186;
        case 187:
            return varc_quickchat_listdialog_187;
        case 188:
            return varc_quickchat_listdialog_188;
        case 189:
            return varc_quickchat_listdialog_189;
        case 190:
            return varc_quickchat_listdialog_190;
        case 191:
            return varc_quickchat_listdialog_191;
        case 192:
            return varc_quickchat_listdialog_192;
        case 193:
            return varc_quickchat_listdialog_193;
        case 194:
            return varc_quickchat_listdialog_194;
        case 195:
            return varc_quickchat_listdialog_195;
        case 196:
            return varc_quickchat_listdialog_196;
        case 197:
            return varc_quickchat_listdialog_197;
        case 198:
            return varc_quickchat_listdialog_198;
        case 199:
            return varc_quickchat_listdialog_199;
        case 200:
            return varc_quickchat_listdialog_200;
        case 201:
            return varc_quickchat_listdialog_201;
        case 202:
            return varc_quickchat_listdialog_202;
        case 203:
            return varc_quickchat_listdialog_203;
        case 204:
            return varc_quickchat_listdialog_204;
        case 205:
            return varc_quickchat_listdialog_205;
        case 206:
            return varc_quickchat_listdialog_206;
        case 207:
            return varc_quickchat_listdialog_207;
        case 208:
            return varc_quickchat_listdialog_208;
        case 209:
            return varc_quickchat_listdialog_209;
        case 210:
            return varc_quickchat_listdialog_210;
        case 211:
            return varc_quickchat_listdialog_211;
        case 212:
            return varc_quickchat_listdialog_212;
        case 213:
            return varc_quickchat_listdialog_213;
        case 214:
            return varc_quickchat_listdialog_214;
        case 215:
            return varc_quickchat_listdialog_215;
        case 216:
            return varc_quickchat_listdialog_216;
        case 217:
            return varc_quickchat_listdialog_217;
        case 218:
            return varc_quickchat_listdialog_218;
        case 219:
            return varc_quickchat_listdialog_219;
        case 220:
            return varc_quickchat_listdialog_220;
        case 221:
            return varc_quickchat_listdialog_221;
        case 222:
            return varc_quickchat_listdialog_222;
        case 223:
            return varc_quickchat_listdialog_223;
        case 224:
            return varc_quickchat_listdialog_224;
        case 225:
            return varc_quickchat_listdialog_225;
        case 226:
            return varc_quickchat_listdialog_226;
        case 227:
            return varc_quickchat_listdialog_227;
        case 228:
            return varc_quickchat_listdialog_228;
        case 229:
            return varc_quickchat_listdialog_229;
        case 230:
            return varc_quickchat_listdialog_230;
        case 231:
            return varc_quickchat_listdialog_231;
        case 232:
            return varc_quickchat_listdialog_232;
        case 233:
            return varc_quickchat_listdialog_233;
        case 234:
            return varc_quickchat_listdialog_234;
        case 235:
            return varc_quickchat_listdialog_235;
        case 236:
            return varc_quickchat_listdialog_236;
        case 237:
            return varc_quickchat_listdialog_237;
        case 238:
            return varc_quickchat_listdialog_238;
        case 239:
            return varc_quickchat_listdialog_239;
        case 240:
            return varc_quickchat_listdialog_240;
        case 241:
            return varc_quickchat_listdialog_241;
        case 242:
            return varc_quickchat_listdialog_242;
        case 243:
            return varc_quickchat_listdialog_243;
        case 244:
            return varc_quickchat_listdialog_244;
        case 245:
            return varc_quickchat_listdialog_245;
        case 246:
            return varc_quickchat_listdialog_246;
        case 247:
            return varc_quickchat_listdialog_247;
        case 248:
            return varc_quickchat_listdialog_248;
        case 249:
            return varc_quickchat_listdialog_249;
    }
    return 0;
}
