/// <reference path="../cs2.d.ts" />
/// <reference path="../gamevals.d.ts" />
/// <reference path="../vars.d.ts" />
// cs2_6073

function cs2_6073(): void {
    varc_toolbelt_rand_key_1 = 0;
    varc_toolbelt_rand_key_2 = 0;
    varc_toolbelt_rand_key_3 = 0;
    varc_toolbelt_rand_key_4 = 0;
    varc_toolbelt_rand_key_5 = 0;
    varc_toolbelt_rand_key_6 = 0;
    varc_toolbelt_rand_key_7 = 0;
    varc_toolbelt_rand_key_8 = 0;
    varc_toolbelt_rand_key_9 = 0;
    varc_toolbelt_rand_key_10 = 0;
    varc_toolbelt_rand_key_11 = 0;
    varc_toolbelt_rand_key_12 = 0;
    varc_toolbelt_rand_key_13 = 0;
    varc_toolbelt_rand_key_14 = 0;
    varc_toolbelt_rand_key_15 = 0;
    varc_toolbelt_rand_key_16 = 0;
    varc_toolbelt_rand_key_17 = 0;
    varc_toolbelt_rand_key_18 = 0;
    varc_toolbelt_rand_key_19 = 0;
    varc_toolbelt_rand_key_20 = 0;
    varc_toolbelt_rand_key_21 = 0;
    varc_toolbelt_rand_key_22 = 0;
    varc_toolbelt_rand_key_23 = 0;
    varc_toolbelt_rand_key_24 = 0;
    varc_toolbelt_rand_key_25 = 0;
    varc_toolbelt_rand_key_26 = 0;
    varc_toolbelt_rand_key_27 = 0;
    varc_toolbelt_rand_key_28 = 0;
    varc_toolbelt_rand_key_29 = 0;
    varc_toolbelt_rand_key_30 = 0;
    varc_toolbelt_rand_key_31 = 0;
    varc_toolbelt_rand_key_32 = 0;
    varc_toolbelt_rand_key_33 = 0;
    varc_toolbelt_rand_key_34 = 0;
    varc_toolbelt_rand_key_35 = 0;
    varc_toolbelt_rand_key_36 = 0;
    varc_toolbelt_rand_key_37 = 0;
    varc_toolbelt_rand_key_38 = 0;
    varc_toolbelt_rand_key_39 = 0;
    varc_toolbelt_rand_key_40 = 0;
    varc_toolbelt_rand_key_41 = 0;
    varc_toolbelt_rand_key_42 = 0;
    varc_toolbelt_rand_key_43 = 0;
    varc_toolbelt_rand_key_44 = 0;
    varc_toolbelt_rand_key_45 = 0;
    varc_toolbelt_rand_key_46 = 0;
    varc_toolbelt_rand_key_47 = 0;
    varc_toolbelt_rand_key_48 = 0;
    varc_toolbelt_rand_key_49 = 0;
    varc_toolbelt_rand_key_50 = 0;
    varc_toolbelt_rand_key_51 = 0;
    varc_toolbelt_rand_key_52 = 0;
    varc_toolbelt_rand_key_53 = 0;
    varc_toolbelt_rand_key_54 = 0;
    varc_toolbelt_rand_key_55 = 0;
    varc_toolbelt_rand_key_56 = 0;
    varc_toolbelt_rand_key_57 = 0;
    varc_toolbelt_rand_key_58 = 0;
    varc_toolbelt_rand_key_59 = 0;
    varc_toolbelt_rand_key_60 = 0;
    varc_toolbelt_rand_key_61 = 0;
    varc_toolbelt_rand_key_62 = 0;
    varc_toolbelt_rand_key_63 = 0;
    varc_toolbelt_rand_key_64 = 0;
}
