/// <reference path="../cs2.d.ts" />
/// <reference path="../gamevals.d.ts" />
/// <reference path="../vars.d.ts" />
// cs2_1580

function cs2_1580(): void {
    ifSetText("Bre'egth: " + "<br>" + "<br>" + "Aggressive female ork found patrolling Zanaris near the windmill." + "<br>" + "<br>" + " Intelligence leads us to believe that a recent fist fight with a subordinate left Bre'egth with one less tooth in her head, and one subordinate", Component.interface_972.component_972_29);
    ifSetText("permanently relocated somewhere else. " + "<br>" + "<br>" + "Her bragging is well known throughout Zanaris, however, she is important to 'Bad Daddy's' plans. Without her, the ork warrior grunts would simply be fighting each other and their superiors. She keeps them in check." + "<br>" + " " + "<br>" + "Suggest first talking to Bre'egth - she's likely to recount the entire story to you if you ask. The trouble might be in getting away again afterwards.", Component.interface_972.component_972_30);
    ifSetText("Gromblod: " + "<br>" + "<br>" + "Mango-mad ork found in the Enchanted Valley. " + "<br>" + "<br>" + "His teeth are so rotten that he can only eat soft fruit, hence his preference for mangos.", Component.interface_972.component_972_23);
    ifSetText("According to reports, he's creating a bit of a nuisance of himself in the Enchanted Valley. " + "<br>" + "<br>" + "The locals don't want to give him the secret to where the magic mango tree is. " + "<br>" + "<br>" + "They're afraid he'll consume the entire harvest and they're probably right." + "<br>" + "<br>" + " Fairy ring code: BKQ.", Component.interface_972.component_972_24);
    ifSetText("Shredflesh: " + "<br>" + "<br>" + "A complete brute to look at, but suspect he's a real teddy bear inside. " + "<br>" + "<br>" + "Last reports place him in a cavern in the Gu'Tanoth region. He's searching for herbs to control his excruciating toothache.", Component.interface_972.component_972_18);
    ifSetText("He needs a dentist, so you may be able to convince him that it's the right thing to do." + "<br>" + "<br>" + "Fairy ring code: ALP.", Component.interface_972.component_972_19);
    ifSetText("Fairy Godfather " + "<br>" + "Code name: 'Bad Daddy':" + "<br>" + "The main villain; he needs to be stopped." + "<br>" + "<br>" + " Located in a separated off section of Zanaris, he's discovered a weakness in the interplanar fabric. This is really bad news for us!", Component.interface_972.component_972_13);
    ifSetText("'Bad Daddy' has used his magic and the magic of the Fairy Queen to make a rift between this plane and another seemingly filled with orks. He's using the rift to transport orks through to use as henchmen." + "<br>" + "<br>" + "The Godfather is invulnerable to any standard attack. His magic is somehow linked to orks, so we suspect some sort of weakness there.", Component.interface_972.component_972_14);
    ifSetText("Ork teeth: Crude and brutal, these masticating marvels convey a feeling of basic primal energy." + "<br>" + "<br>" + "What they lack in quality, they more than make up for in their wonderfully coarse, brutal and businesslike functionality.", Component.interface_972.component_972_9);
    ifSetText("In the host's early years, the tooth comes to an excessively tantalising point! " + "<br>" + "<br>" + "As the host grazes most of the time, this quickly gets worn down. " + "<br>" + "<br>" + "Opinion is divided, but many believe the more interesting teeth come from those orks more accustomed to combat. A broken tooth sometimes creates a sublime 'organic' structure - smooth and discoloured, but dense.", Component.interface_972.component_972_10);
}
