import hashlib, shutil
from .codec import *
from .specs import MAPS,BLOCKED
from .compat import decode_surface_compat

def find(root,name,exact):
    items=[p for p in (root.rglob(name) if exact else root.rglob('*')) if p.is_file() and (exact or p.as_posix().endswith(name))]
    if len(items)!=1: raise ConversionError(f'find {name}: {len(items)} matches')
    return items[0]

def audit(repo,a):
    ids=sorted({r[0] for r in a})
    missing=[i for i in ids if not (repo/'config_loc'/f'{i}.json').is_file()]
    return {'distinct_ids':len(ids),'existing_727_definition_ids':len(ids)-len(missing),'missing_727_definition_ids':missing,'semantic_compatibility':'pending visual/remap audit'}

def convert_region(repo,ext,out,m,r):
    label,region,map_name,land_name,under_name,underland_name,exact,known=r
    root=ext/m[2]
    mp=find(root,map_name,exact); mb=payload(mp)
    t,ef,mx,tile_bytes=decode_surface_compat(mb,m[1]+'/'+label)
    rd=out/m[0]/'maps'/region
    write_json(rd/'terrain.json',terrain_json(region,4,t,ef))
    res={'label':label,'staged_region':region,'source_region_known':known,'output':str(rd.relative_to(repo)),
         'surface':{'source_file':str(mp.relative_to(ext)),'source_bytes':len(mb),'sha256':hashlib.sha256(mb).hexdigest(),'tile_bytes':tile_bytes,'effects':[e['type'] for e in ef],'maxima':dict(mx)}}
    if land_name:
        lp=find(root,land_name,exact); lb=payload(lp)
        a,g,end=decode_locs(lb)
        if end!=len(lb): raise ConversionError('location trailing bytes')
        canonical=encode_locs(a); a2,_,end2=decode_locs(canonical)
        if sorted(a2)!=sorted(a) or end2!=len(canonical): raise ConversionError('location round-trip failed')
        write_json(rd/'locs.json',locs_json(region,a))
        res['locations']={'source_file':str(lp.relative_to(ext)),'source_bytes':len(lb),'placements':len(a),'canonical_727_bytes':len(canonical),
                          'empty_legacy_groups_removed':[x[0] for x in g if x[3]==0],'object_audit':audit(repo,a)}
    if under_name:
        up=find(root,under_name,exact); ub=payload(up)
        u,ue,um,retained,note=decode_underwater(ub,m[1]+'/'+label+'/underwater')
        write_json(rd/'underwater_terrain.json',terrain_json(region,1,u,ue))
        res['underwater']={'source_file':str(up.relative_to(ext)),'source_bytes':len(ub),'retained_727_tile_bytes':retained,
                           'normalization':note,'effects':[e['type'] for e in ue],'maxima':dict(um)}
    if underland_name:
        ulp=find(root,underland_name,exact); bb=payload(ulp)
        a,_,end=decode_locs(bb)
        if end!=len(bb): raise ConversionError('underwater location trailing bytes')
        write_json(rd/'underwater_locs.json',locs_json(region,a))
        res.setdefault('underwater',{})['underwater_locations']={'source_file':str(ulp.relative_to(ext)),'source_bytes':len(bb),
                                                                  'placements':len(a),'object_audit':audit(repo,a)}
    return res

def report(rs):
    z=['# Public custom map to revision 727 conversion status','',
       'Generated by tools/convert_public_custom_maps.py. Raw third-party archives remain temporary and are not committed.','',
       'Conversion means the released terrain and location streams decoded and were emitted as Burial Grounds native editable map JSON. Final Custom Mode placement and semantic object remapping happen after all layouts are compared.','',
       '| Map | Status | Regions | Placements | Missing 727 loc IDs | Notes |',
       '| --- | --- | ---: | ---: | ---: | --- |']
    for x in rs:
        placements=0; missing=set(); notes=[]
        for r in x.get('regions',[]):
            if r.get('locations'):
                placements+=r['locations']['placements']
                missing.update(r['locations']['object_audit']['missing_727_definition_ids'])
            if r.get('underwater',{}).get('underwater_locations'):
                placements+=r['underwater']['underwater_locations']['placements']
                missing.update(r['underwater']['underwater_locations']['object_audit']['missing_727_definition_ids'])
            if not r['source_region_known']:
                notes.append(f"{r['label']} source coords unknown; staged at {r['staged_region']}")
        if x['note']: notes.append(x['note'])
        if x.get('error'): notes.append(x['error'])
        z.append(f"| {x['name']} | **{x['status']}** | {len(x.get('regions',[]))} | {placements} | {len(missing)} | {'; '.join(notes) or 'none'} |")
    z.append(f"| {BLOCKED['name']} | **{BLOCKED['status']}** | 0 | 0 | - | {BLOCKED['reason']} |")
    z+=['','## Details','']
    for x in rs:
        z += [f"### {x['name']}",f"- Status: **{x['status']}**",f"- Role: {x['role']}"]
        if x['note']: z.append('- Note: '+x['note'])
        if x.get('error'):
            z += ['- Error: '+x['error'],'']
            continue
        for r in x['regions']:
            s=r['surface']
            z.append(f"- {r['label']} -> {r['staged_region']}: surface {s['source_bytes']} bytes; 727 tile grammar PASS; effects {s['effects'] or 'none'}")
            if r.get('locations'):
                a=r['locations']['object_audit']
                z.append(f"  - {r['locations']['placements']} loc placements; {a['distinct_ids']} IDs; {a['existing_727_definition_ids']} numeric IDs exist; {len(a['missing_727_definition_ids'])} absent; semantics still require visual/remap audit")
            if r.get('underwater'):
                z.append('  - underwater: '+r['underwater'].get('normalization','locations only'))
            z.append('  - output: '+r['output'])
        z.append('')
    z += ['## Blocked release','',
          f"- **{BLOCKED['name']}**: {BLOCKED['reason']}",
          '- Former release target: '+BLOCKED['source'],'',
          '## After conversion','',
          '1. Compare all converted layouts against the existing 72_200 through 77_205 Custom Mode footprint and choose final spare regions.',
          '2. Normalize implicit heights where relocation would change terrain silhouette.',
          '3. Visually audit and remap object definitions; numeric ID existence alone is not semantic compatibility.',
          '4. Build a disposable 727 cache and test collision, bridges and levels, minimap, desktop, and Android.','']
    return '\n'.join(z)

def run(repo,ext,out):
    out.mkdir(parents=True,exist_ok=True)
    for m in MAPS:
        if (out/m[0]).exists(): shutil.rmtree(out/m[0])
    results=[]; failures=0
    for m in MAPS:
        x={'slug':m[0],'name':m[1],'role':m[3],'note':m[4],'regions':[]}
        try:
            for r in m[5]:
                x['regions'].append(convert_region(repo,ext,out,m,r))
            x['status']='CONVERTED'
        except Exception as e:
            failures+=1
            x['status']='FAILED'
            x['error']=str(e)
            shutil.rmtree(out/m[0],ignore_errors=True)
        results.append(x)
        print(x['status'],m[1],x.get('error',''))
    write_json(out/'conversion-status.json',{'generated_by':'tools/convert_public_custom_maps.py','maps':results,'blocked':[BLOCKED]})
    (repo/'docs'/'custom-map-conversion-status.md').write_text(report(results),encoding='utf-8')
    return failures
